broyden1 – SciFortran
broyden1 Subroutine
121 statements
Source File
public subroutine broyden1(ff, x, check, maxits, tol, tol1, tolmin, stpmx, noexit)
Arguments
Type Intent Optional Attributes Name
procedure(broydn_func) :: ff
real(kind=8), intent(inout), dimension(:) :: x
logical, optional :: check
integer, optional :: maxits
real(kind=8), optional :: tol
real(kind=8), optional :: tol1
real(kind=8), optional :: tolmin
real(kind=8), optional :: stpmx
logical, optional :: noexit
Calls
Contents
Call graph
broyden1 calls fdjac, get_diag, lnsrch, lower_triangle, outerprod, put_diag, qrdcmp, qrupdt, rsolv, unit_matrix, vabs
fdjac calls assert_eq4
get_diag calls assert_eq2
lnsrch calls vabs, assert_eq4
lower_triangle calls outerdiff
put_diag calls assert_eq2
qrdcmp calls outerprod, vabs, assert_eq4
qrupdt calls assert_eqn, ifirstloc
rsolv calls assert_eq4