cfft_1d_backward – SciFortran
cfft_1d_backward Subroutine
28 statements
Source File
public subroutine cfft_1d_backward(func)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(inout), dimension(:) :: func
Calls
Called by
Contents
Source Code
cfft_1d_backward
Source Code
  subroutine cfft_1d_backward(func)
    complex(8),dimension(:),intent(inout) :: func
    real(8),dimension(:),allocatable      :: wsave,work
    integer                               :: N,lenwrk,lensav,lenc,inc,ier
    N      = size(func)
    lenwrk = 2*N
    lensav = 2*N + int( log(dble(N))/log(2.d0) ) + 4
    lenc   = N
    inc    = 1
    allocate(wsave(lensav))
    call cfft1i(N,wsave,lensav,ier)
    if(ier==2)stop "cfft_1d_backward: LENSAV not big enough"
    allocate(work(lenwrk))
    call cfft1b(N,inc,func,lenc,wsave,lensav,work,lenwrk,ier)
    deallocate(wsave,work)
    select case(ier)
    case (0)
       return
    case (1)
       stop "cfft_1d_backward: LENC not big enough"
    case (2)
       stop "cfft_1d_backward: LENSAV not big enough"
    case (3)
       stop "cfft_1d_backward: LENWRK not big enough"
    case (20)
       stop "cfft_1d_backward: input error returned by lower level routine"
    end select
  end subroutine cfft_1d_backward
Call graph
cfft_1d_backward calls cfft1b, cfft1i
ifft calls cfft_1d_backward