CGBD – SciFortran
CGBD Subroutine
51 statements
Source File
subroutine CGBD(IPRINT, ITER, NFUN, GNORM, N, X, F, G, STP, FINISH, NDES, IM, BETAFR, BETAPR, BETA)
Arguments
Type Intent Optional Attributes Name
integer :: IPRINT(2)
integer :: ITER
integer :: NFUN
double precision :: GNORM
integer :: N
double precision :: X(N)
double precision :: F
double precision :: G(N)
double precision :: STP
logical :: FINISH
integer :: NDES
integer :: IM
double precision :: BETAFR
double precision :: BETAPR
double precision :: BETA
Calls
Called by
Contents
Call graph
cgbd calls 2, 6
cgfam calls cgbd
fmin_cgplus_df calls cgfam
fmin_cgplus_f calls cgfam