csphjy – SciFortran
csphjy Subroutine
81 statements
Source File
public subroutine csphjy(n, z, nm, csj, cdj, csy, cdy)
************80
! CSPHJY: spherical Bessel functions jn(z) and yn(z) for complex argument.
Discussion:
This procedure computes spherical Bessel functions jn(z) and yn(z)
and their derivatives for a complex argument.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
01 August 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) N, the order of jn(z) and yn(z).
Input, complex (kind = 8) Z, the argument.
Output, integer (kind = 4) NM, the highest order computed.
Output, complex (kind = 8) CSJ(0:N0, CDJ(0:N), CSY(0:N), CDY(0:N),
the values of jn(z), jn'(z), yn(z), yn'(z).
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: n
complex(kind=8) :: z
integer(kind=4) :: nm
complex(kind=8) :: csj(0:n)
complex(kind=8) :: cdj(0:n)
complex(kind=8) :: csy(0:n)
complex(kind=8) :: cdy(0:n)
Calls
Contents
Call graph
csphjy calls msta1, msta2
msta1 calls envj
msta2 calls envj