daxpy – SciFortran
daxpy Subroutine
31 statements
Source File
subroutine daxpy(n, da, dx, incx, dy, incy)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: da
double precision :: dx(1)
integer :: incx
double precision :: dy(1)
integer :: incy
Called by
Contents
Call graph
cauchy calls daxpy, bmv
dtrsl calls daxpy
dvdrvr calls daxpy, newvec
orthnrm calls daxpy
bmv calls dtrsl
dvdson calls dvdrvr
formk calls dtrsl
mainlb calls cauchy, formk, subsm, cmprlb
newvec calls orthnrm
subsm calls dtrsl
cmprlb calls bmv
dvdson_eigh_d calls dvdson
setulb calls mainlb
bfgs_no_grad calls setulb
bfgs_with_grad calls setulb