dcopy – SciFortran
dcopy Subroutine
33 statements
Source File
subroutine dcopy(n, dx, incx, dy, incy)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: dx(1)
integer :: incx
double precision :: dy(1)
integer :: incy
Called by
Contents
Call graph
cauchy calls dcopy
dvdrvr calls dcopy, multbc, newvec
dvdson calls dcopy, dvdrvr
formk calls dcopy
lnsrlb calls dcopy
mainlb calls dcopy, cauchy, formk, lnsrlb, matupd, subsm
matupd calls dcopy
multbc calls dcopy
orthnrm calls dcopy
subsm calls dcopy
dvdson_eigh_d calls dvdson
newvec calls orthnrm
setulb calls mainlb
bfgs_no_grad calls setulb
bfgs_with_grad calls setulb