dscal – SciFortran
dscal Subroutine
26 statements
Source File
subroutine dscal(n, da, dx, incx)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: da
double precision :: dx(1)
integer :: incx
Called by
Contents
Call graph
addabs calls dscal
cauchy calls dscal
dvdson calls dscal, dvdrvr, setup
mainlb calls dscal, cauchy, subsm
orthnrm calls dscal
subsm calls dscal
dvdrvr calls addabs, newvec
dvdson_eigh_d calls dvdson
newvec calls orthnrm
setulb calls mainlb
setup calls addabs
bfgs_no_grad calls setulb
bfgs_with_grad calls setulb