DVDSON – SciFortran
DVDSON Subroutine
85 statements
Source File
subroutine DVDSON(OP, N, LIM, DIAG, ILOW, IHIGH, ISELEC, NIV, MBLOCK, CRITE, CRITC, CRITR, ORTHO, MAXITER, WORK, IWRSZ, IWORK, IIWSZ, HIEND, NLOOPS, NMV, IERR)
Arguments
Type Intent Optional Attributes Name
real :: OP
integer :: N
integer :: LIM
real :: DIAG
integer :: ILOW
integer :: IHIGH
integer :: ISELEC
integer :: NIV
integer :: MBLOCK
real :: CRITE
real :: CRITC
real :: CRITR
real :: ORTHO
integer :: MAXITER
real :: WORK
integer :: IWRSZ
integer :: IWORK
integer :: IIWSZ
logical :: HIEND
integer :: NLOOPS
integer :: NMV
integer :: IERR
Calls
Called by
Contents
Call graph
dvdson calls dcopy, dscal, dvdrvr, setup
dvdrvr calls dcopy, dspevx, addabs, daxpy, ddot, multbc, newvec, ovflow
setup calls addabs, dinit
addabs calls dscal, ddot
multbc calls dcopy, dgemv
newvec calls dgemv, dnrm2, orthnrm
ovflow calls dinit
orthnrm calls dcopy, dscal, daxpy, ddot
dvdson_eigh_d calls dvdson