gammaf – SciFortran
gammaf Subroutine
48 statements
Source File
public subroutine gammaf(x, ga)
************80
! GAMMA evaluates the Gamma function.
Licensing:
The original FORTRAN77 version of this routine is copyrighted by
Shanjie Zhang and Jianming Jin.  However, they give permission to
incorporate this routine into a user program that the copyright
is acknowledged.
Modified:
08 September 2007
Author:
Original FORTRAN77 version by Shanjie Zhang, Jianming Jin.
FORTRAN90 version by John Burkardt.
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45
Parameters:
Input, real (kind = 8) X, the argument.
X must not be 0, or any negative integer.
Output, real (kind = 8) GA, the value of the Gamma function.
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: x
real(kind=8) :: ga
Called by
Contents
Call graph
betaf calls gammaf
cchg calls gammaf
chgm calls gammaf
chgubi calls gammaf
chguit calls gammaf
chgus calls gammaf
cikva calls gammaf
cikvb calls gammaf
cjyva calls gammaf
cjyvb calls gammaf
dvla calls gammaf, vvla
dvsa calls gammaf
hygfx calls gammaf
hygfz calls gammaf
ikv calls gammaf
incog calls gammaf
jyv calls gammaf
stvhv calls gammaf
stvlv calls gammaf
vvla calls gammaf, dvla
vvsa calls gammaf
chgu calls chgubi, chguit, chgus
incob calls betaf
pbdv calls dvla, dvsa
pbvv calls vvla, vvsa