igrnd – SciFortran
igrnd Function
8 statements
Source File
function igrnd(l, h)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: l
integer, intent(in) :: h
Return Value integer
Calls
Contents
Source Code
igrnd
Source Code
integer function igrnd(l,h)
  integer,intent(in) :: l,h
  real(8)            :: u,r
  u=grnd()
  r=(h-l+1)*u+l
  igrnd=int(r)
  return
end function igrnd
Call graph
igrnd calls grnd
grnd calls mt, sgrnd
sgrnd calls mt