Init_MPI – SciFortran
Init_MPI Subroutine
10 statements
Source File
public subroutine Init_MPI(comm, msg)
Arguments
Type Intent Optional Attributes Name
integer, optional :: comm
logical, optional :: msg
Calls
Contents
Source Code
Init_MPI
Source Code
  subroutine Init_MPI(comm,msg)
    integer,optional :: comm
    logical,optional :: msg
    call MPI_Init(ierr)
    call Error_MPI(ierr,"MPI_Start")
    if(present(comm))comm=MPI_COMM_WORLD
    if(present(msg))then
       if(msg)call StartMsg_MPI(MPI_COMM_WORLD)
    endif
  end subroutine Init_MPI
Call graph
init_mpi calls mpi_init, error_mpi, startmsg_mpi
startmsg_mpi calls mpi_barrier, get_rank_mpi, get_size_mpi
get_rank_mpi calls error_mpi, mpi_comm_rank
get_size_mpi calls error_mpi, mpi_comm_size