mainlb – SciFortran
mainlb Subroutine
328 statements
Source File
subroutine mainlb(n, m, x, l, u, nbd, f, g, factr, pgtol, ws, wy, sy, ss, wt, wn, snd, z, r, d, t, xp, wa, index, iwhere, indx2, task, iprint, csave, lsave, isave, dsave)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: m
double precision :: x(n)
double precision :: l(n)
double precision :: u(n)
integer :: nbd(n)
double precision :: f
double precision :: g(n)
double precision :: factr
double precision :: pgtol
double precision :: ws(n,m)
double precision :: wy(n,m)
double precision :: sy(m,m)
double precision :: ss(m,m)
double precision :: wt(m,m)
double precision :: wn(2*m,2*m)
double precision :: snd(2*m,2*m)
double precision :: z(n)
double precision :: r(n)
double precision :: d(n)
double precision :: t(n)
double precision :: xp(n)
double precision :: wa(8*m)
integer :: index(n)
integer :: iwhere(n)
integer :: indx2(n)
character(len=60) :: task
integer :: iprint
character(len=60) :: csave
logical :: lsave(4)
integer :: isave(23)
double precision :: dsave(29)
Calls
Called by
Contents
Call graph
mainlb calls active, cauchy, cmprlb, dcopy, dscal, errclb, formk, formt, freev, lnsrlb, matupd, prn1lb, prn2lb, prn3lb, projgr, subsm, timer
cauchy calls dcopy, dscal, bmv, daxpy, hpsolb
cmprlb calls bmv
formk calls dcopy, dpofa, dtrsl
formt calls dpofa
lnsrlb calls dcopy, dcsrch
matupd calls dcopy
prn2lb calls 2
prn3lb calls 2
subsm calls dcopy, dscal, dtrsl
timer calls sngl
bmv calls dtrsl
dcsrch calls dcstep
dtrsl calls daxpy
setulb calls mainlb
bfgs_no_grad calls setulb
bfgs_with_grad calls setulb