minimize_sascha_ – SciFortran
minimize_sascha_ Subroutine
200 statements
Source File
subroutine minimize_sascha_(funct, N, X, F, G, H, W, DFN, XM, HH, EPS, MODE, MAXFN, IPRINT, IEXIT, ITN)
Arguments
Type Intent Optional Attributes Name
real :: funct
integer :: N
double precision :: X(*)
double precision :: F
double precision :: G(*)
double precision :: H(*)
double precision :: W(*)
double precision :: DFN
double precision :: XM(*)
double precision :: HH
double precision :: EPS
integer :: MODE
integer :: MAXFN
integer :: IPRINT
integer :: IEXIT
integer :: ITN
Calls
Called by
Contents
Call graph
minimize_sascha_ calls fd05ad, mc11ad, mc11bd, mc11ed
fmin_cgminimize_func calls minimize_sascha_
fmin_cgminimize_sub calls minimize_sascha_