NEWVEC – SciFortran
NEWVEC Subroutine
49 statements
Source File
subroutine NEWVEC(N, NUME, LIM, MBLOCK, KPASS, CRITR, ORTHO, NNCV, INCV, DIAG, SVEC, EIGVAL, AB, BASIS, ICV, RESTART, DONE)
Arguments
Type Intent Optional Attributes Name
integer :: N
integer :: NUME
integer :: LIM
integer :: MBLOCK
integer :: KPASS
real :: CRITR
real :: ORTHO
integer :: NNCV
integer :: INCV
real :: DIAG
real :: SVEC
real :: EIGVAL
real :: AB
real :: BASIS
integer :: ICV
logical :: RESTART
logical :: DONE
Calls
Called by
Contents
Call graph
newvec calls dgemv, dnrm2, orthnrm
orthnrm calls daxpy, dcopy, ddot, dscal
dvdrvr calls newvec
dvdson calls dvdrvr
dvdson_eigh_d calls dvdson