pbvv – SciFortran
pbvv Subroutine
149 statements
Source File
public subroutine pbvv(v, x, vv, vp, pvf, pvd)
************80
! PBVV computes parabolic cylinder functions Vv(x) and their derivatives.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
29 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, real (kind = 8) V, the order.
Input, real (kind = 8) X, the argument.
Output, real (kind = 8) VV(0:*), VP(0:*), the values of Vv(x), Vv'(x).
Output, real (kind = 8) PVF, PVD, the values of Vv(x) and Vv'(x).
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: v
real(kind=8) :: x
real(kind=8) :: vv(0:*)
real(kind=8) :: vp(0:*)
real(kind=8) :: pvf
real(kind=8) :: pvd
Calls
Contents
Call graph
pbvv calls vvla, vvsa
vvla calls dvla, gammaf
vvsa calls gammaf
dvla calls vvla, gammaf