pdf_sdev_1d – SciFortran
pdf_sdev_1d Function
6 statements
Source File
function pdf_sdev_1d(self) result(sdev)
Arguments
Type Intent Optional Attributes Name
type(pdf_kernel) :: self
Return Value real(kind=8)
Calls
Called by
Contents
Source Code
pdf_sdev_1d
Source Code
function pdf_sdev_1d(self) result(sdev)
  type(pdf_kernel) :: self
  real(8)          :: var,sdev
  var  = pdf_var_1d(self)
  sdev = sqrt(var)
end function pdf_sdev_1d
Call graph
pdf_sdev_1d calls pdf_var_1d
pdf_var_1d calls pdf_mean_1d, simps
pdf_mean_1d calls simps
pdf_print_moments_pfile_1d calls pdf_sdev_1d, pdf_skew_1d
pdf_skew_1d calls pdf_sdev_1d