sckb – SciFortran
sckb Subroutine
66 statements
Source File
public subroutine sckb(m, n, c, df, ck)
************80
! SCKB: expansion coefficients for prolate and oblate spheroidal functions.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
15 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) M, the mode parameter.
Input, integer (kind = 4) N, the mode parameter.
Input, real (kind = 8) C, the spheroidal parameter.
Input, real (kind = 8) DF(*), the expansion coefficients DK.
Output, real (kind = 8) CK(*), the expansion coefficients CK.
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: m
integer(kind=4) :: n
real(kind=8) :: c
real(kind=8) :: df(200)
real(kind=8) :: ck(200)
Called by
Contents
Call graph
aswfa calls sckb
rmn1 calls sckb
rmn2so calls sckb, rmn1
rswfo calls rmn1, rmn2so
rswfp calls rmn1