sgrnd – SciFortran
sgrnd Subroutine
8 statements
Source File
subroutine sgrnd(seed)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: seed
Calls
Called by
Contents
Source Code
sgrnd
Source Code
subroutine sgrnd(seed)
  ! Setting initial seeds to mt[N] using the generator Line 25 of Table 1 in
  ! [KNUTH 1981, The Art of Computer Programming Vol. 2 (2nd Ed.), pp102]
  integer,intent(in) :: seed
  mt(0) = iand(seed,-1)
  do mti=1,N-1
     mt(mti) = iand(69069 * mt(mti-1),-1)
  enddo
  return
end subroutine sgrnd
Call graph
sgrnd calls mt
grnd calls sgrnd
gaussrnd calls grnd
igrnd calls grnd