fftn – SciFortran
fftn Interface
3 statements
Source File
public interface fftn
Calls
Contents
Module Procedures
rfft_nd_forward cfft_nd_forward
Module Procedures
public subroutine rfft_nd_forward(func, N, lot)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(inout), dimension(:) :: func
integer, intent(in) :: N
integer, intent(in) :: lot
public subroutine cfft_nd_forward(func, n, lot)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(inout), dimension(:) :: func
integer, intent(in) :: n
integer, intent(in) :: lot
Call graph
fftn calls cfft_nd_forward, rfft_nd_forward
cfft_nd_forward calls cfftmf, cfftmi
rfft_nd_forward calls rfftmf, rfftmi